name: CI

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install numpy
      - name: Run verifiers
        run: |
          python src/verify_gaps.py examples/core_banach/example_core.json --type core_banach --verified
          python src/verify_gaps.py examples/ledger/example_ledger.json --type ledger --verified
          python src/verify_gaps.py examples/coupled_streams/example_coupled.json --type coupled_stream
